CREATE SEQUENCE ID_BON_DE_COMMANDE_SEQ;

CREATE SEQUENCE ID_BON_DE_RECEPTION_SEQ;

CREATE SEQUENCE ID_DEMANDE_ACHAT_SEQ;

CREATE SEQUENCE ID_DETAILS_BON_DE_COMMANDE_SEQ;

CREATE SEQUENCE ID_DETAILS_BON_DE_RECEPTION_SEQ;

CREATE SEQUENCE ID_DETAILS_DEMANDE_ACHAT_SEQ;

CREATE SEQUENCE ID_PRODUIT_SEQ;

CREATE SEQUENCE ID_UNITE_SEQ;

CREATE SEQUENCE ID_CHAINE_APPROBATION_SEQ;

CREATE SEQUENCE ID_NIVEAU_VALIDATION_SEQ;

CREATE SEQUENCE ID_DETAILS_MOUVEMENT_STOCK_SEQ;

CREATE SEQUENCE ID_MOUVEMENT_STOCK_SEQ;

CREATE SEQUENCE ID_ANTECEDENT_SEQ;

CREATE SEQUENCE ID_TIERS_SEQ;

CREATE SEQUENCE ID_DEPARTEMENT_SEQ;

CREATE SEQUENCE ID_UTILISATEUR_SEQ;
